version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - "80:80"
      - "433:433"
    environment:
      APP_NAME: php-fpm
    volumes:
      - .:/var/www/
      - ./Docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Docker/nginx/logs:/var/log/nginx
  pgsql:
    image: 'postgres:14'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_ROOT_PASSWORD: secret
      POSTGRES_DB: data
    volumes:
      - ./Docker/Pgsql.php:/var/lib/Pgsql.php
#    command:
#      - --default-authentication-plugin=pgsql_native_password
  php-fpm:
    build:
      context: ./Docker/php-fpm
    volumes:
      - .:/var/www
      - ./Docker/app/php.ini:/usr/local/etc/php/custom.d
