<?php include 'layouts/header.phtml' ?>
<main>
    <?php $message = $message ?? "";?>
    <?= $message ?>
    <form action="/login" method="post">

        <?php $login = $login ?? "";?>
        Логин: <input type="text" name="login" placeholder= "тел. или email" value="<?= $login ?>"/>

        Пароль: <input type="password" name="password" placeholder="пароль"/>
        <input type="submit" value="Войти" name="log_in" />

    </form>
</main>
<?php include 'layouts/footer.phtml' ?>

