<?php include 'layouts/header.phtml' ?>
    <main>
        <form action="/registration" method="post">
            <?php if (isset($data['error'])) : ?>
            <p>
                <?php foreach ($data['error'] as $item) : ?>
                <p>
                    Error: <?= $item ?>
                </p>
                <?php endforeach; ?>

            </p>
            <?php endif; ?>
            <p>Name: <input type="text" name="name" placeholder= "IlonMask" value="<?= $data['name'] ?? "" ?>"/></p>
            <p>Phone: <input type="text" name="number" placeholder= "123456789" value="<?= $data['number'] ?? "" ?>"/></p>
            <p>Email: <input type="text" name="email" placeholder= "Ilon@musk.ru" value="<?= $data['email'] ?? "" ?>"/></p>
            <p>Password: <input type="password" name="password" placeholder="********"/></p>
            <p>Password: <input type="password" name="password_duplicate" placeholder="********"/></p>
            <p><input type="submit" value="Registration" name="register" /></p>
        </form>
    </main>
<?php include 'layouts/footer.phtml' ?>

