<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>OnlyTeam Test</title>
</head>
<body>
<nav style="margin-bottom: 100px">
    <a href="/">Main</a>
    <a href="/show">Show</a>
    <?php if (isset($_SESSION['session'])) : ?>
        <a href="/logout">Logout</a>
    <?php else : ?>
        <a href="/login">Login</a>
        <a href="/registration">Registration</a>
    <?php endif;?>
</nav>
